package.json, yarn.lock
When we renamed the packages, we moved the cli outside of the @forestryio scoping.
Switch to use the new npm package, and move dep to devDependencies
=> Switch cli to use unscoped package

utils/index.ts
Show error when we're missing Tina Cloud env. Without this, it's a bit of a cryptic error from the underlying graphql query
=> Show error when we're missing Tina Cloud env

package.json, yarn.lock
Bump tina-graphql-gateway version to include blocks reordering fix.
fixes #11
=> bump tina-graphql-gateway version

package.json, yarn.lock
old version had tinajs.dev hardcoded in auth popup
=> fix: uses version of gql-gateway with fixed auth

components/document-renderer.tsx
Updates the error messaging when a Renderer is missing for a specific `__typename`.
=> Fix: Better error message in DocumentRenderer

package.json, yarn.lock
Branched off of https://github.com/tinacms/tina-cloud-starter/pull/39
Upgrade tina-graphql-gateway package to use updated /currentUser endpoint (required to login to tina cloud)
=> Forestrygql 0.2.3

README.md
.env.local doesn't already exist, the user has to create it but the readme only says to copy the content of another file into it. I know what it means but maybe could be clearer
=> Tell user to create .env.local

components/helper-components.tsx, components/tina-wrapper.tsx, yarn.lock
Replaces the default `tinacms` "empty" placeholder with a `tina-cloud-starter`-friendly "empty" placeholder that points to the `Tina Cloud Client` beta documentation.
**Before:**
**After:**
Closes https://github.com/tinacms/tina-graphql-gateway/issues/166
=> feat: Adds Sidebar Placeholder for Starter

package.json, pages/admin/posts/[filename].tsx, yarn.lock
Provides an example of how to use `filterCollections` param on `useDocumentCreatorPlugin` to `filter` the available options in the "Add Document" Collections field to just the `posts` collection.
This enables a developer to limit when and where a new item can be added to a `collection` via that modal.
=> feat: Filters `collections` options on the `posts` admin

components/tina-wrapper.tsx
Uses `cms.plugins.all()` and `cms.plugins.remove()` to locate and remove the `Media Manager` plugin.  This removes the "Media Manager" option from the Tina Sidebar.
Closes #47
=> 47 - Hides Media Manager in Starter

utils/editState.tsx
Reload window when exiting edit mode since content would be stale from getStaticProps
cc @logan-anderson does this make sense?
=> Data is stale after exiting edit mode

package.json, pages/api/cloudinary/[...media].tsx, yarn.lock
Updates `tina-cloud-next` dependency to `@tinacms/auth`.
=> chore: Use `@tinacms/auth` instead of `tina-cloud-next`

pages/_app.js
Adds `onNewDocument()` and `filterCollections()` via `documentCreatorCallback` for handling when a new document is created (redirecting to the newly-created document) and limiting the Collection choices to just `Blog Posts`.
Closes #106 
Closes https://github.com/tinacms/tinacms/issues/1902
=> chore: Adds documentCreatorCallback

.tina/__generated__/_graphql.json, .tina/__generated__/_schema.json, .tina/__generated__/config/schema.json, .tina/__generated__/schema.gql, .tina/__generated__/types.ts, .tina/schema.ts, components/post.tsx, pages/posts/[filename].tsx
The blog markdown body was saving to the frontmatter due to a bug with Tina, so I've renamed the body field from `_body` to just `body` to resolve the issue.
=> fix blog body saving issue

components/post.tsx
On mobile the image wasn't displaying correctly and especially tall images looked quite bad. This limits the image size without stretching it, but it may get cropped to ensure it doesn't take up too much of the page.
=> add constraints on image size

pages/[filename].tsx
There is an issue right now where the query is not re-run when the variables change.
=> This is a temporary fix for the navigation issues.

README.md
fix #150
Provide install commands and useful URLs as a reminder in the README.
You still have to go through the guide to set up Tina Cloud.
=> docs: install and URLS

pages/_app.js
This enables the ability to disable the edit button if one wants to.  
possible  fix for https://github.com/tinacms/tina-cloud-starter/issues/135
=> edit button can be toggled from env files

components/posts.tsx
When `author` is empty this page fails
=> Add null check for author on post index page

components/placeholder.tsx
Sister PR to https://github.com/tinacms/tinacms/pull/2028
Updates the link in the `NoFormsPlaceholder` to point to the Content Modelling page on tina.io:
https://tina.io/docs/schema/
Related to https://github.com/tinacms/tinacms/issues/2007
=> Updates NoFormsPlaceholder Link

components/post.tsx, components/posts.tsx
This PR adds in some defensive coding measures in the event an invalid date is present in the form.
We are handling this primarily on the backend; however, this can manifest on the frontend when creating a new document, and attempting to formatting a null value will cause the app to break.
=> Handle falsey date values in Posts

.env.local.sample, pages/_app.js
I'm not sure that it's obvious how to edit, once you land on the starter. 
We hid the button by default, because we didn't want it to show up on our hosted tina-cloud-starter, but I think the user needs that extra help to know what to do when they land on the starter for the first time.
=> Hide edit btn env

components/blocks/features.tsx, components/footer.tsx, components/header.tsx, components/icon.tsx
Refactor our Icon component, and fixed a few bugs along the way.
Code cleanup:
- Generate the Tina fields from the type definitions
- Group a few hashes to remove some duplication
- Moved several large constants outside of component
- Removed useMemo (This is a production page, This feels like an over-optimization for edit-mode)
fixes:
- "white" was defined in the circle mode, but not the other
- misleading to use "random" on the frontend to generate an icon (the preview wont reflect the production icon)
- cleanup around "custom" size
- fixed an issue where circle icons wouldn't work in header/footer
Next steps (in a future PR):
- We still have several defensive checks. We should use better types, and make certain Tina fields required
- Several other components likely need a similar …
=> Icon cleanup & fixes

components/posts/post.tsx
The date useEffect was rendering a different value than the server, causing this:
=> Fix issue with hydration on dates

package.json, yarn.lock
As per [✨ Tina.io | Sample Templates and Showing off Tina Features](https://github.com/tinacms/tina.io/issues/1743) there was an issue with the styled-jsx dependency looking for old versions of react. By updating the dependency to the state it is now, it will support the newer versions of react used in Tina CMS
=> Updated styled-jsx dependency to fix out-dated Tailwind starter template

NOTICE
I noticed the starter was still referencing Forestry
=> NOTICE - Change from forestry to SSW

package.json, pnpm-lock.yaml
Relates to https://github.com/tinacms/tinacms/issues/4744
Downgrades the eslint version used from `v9.9.1` to `v8.0.0` to resolve conflicts.
=> Downgrade Eslint to fix install error

package.json, pnpm-lock.yaml
This PR updates the following packages to their latest minor versions:
- [at]tinacms/cli from 1.8.0 to 1.8.1
- tinacms from 2.6.0 to 2.6.1
=> ⬆️ Dependencies - Updates [at]tinacms/cli and tinacms packages to latest

components/nav/header.tsx
Currently, the starter template header nav links will bleed over and be inaccessible on smaller mobile screens
This pr adjusts the header's flex box to wrap the nav links below the icon and title on smaller dimensioned screens.
=> Wrap header nav links on mobile
