yarn.lock
Fixes issue with "esm module not defined" on install/build
=> fix: dep issue with esm

pages/[[...slug]].tsx
Added body to gql request so user can see the body change as they edit it.
=> Added body to request

readme.md
Probably not enough time for folks to watch the video if getting up and running quickly from the readme
=> Remove video walk through link

pages/404.js
Fix #22 
Very basic custom 404 to at least provide to link to go back to the homepage.
=> feat: custom 404

components/cta.tsx, components/page-renderer.tsx, pages/404.js
=> Custom 404

.tina/__generated__/config/front_matter/templates/block-cta.yml, .tina/__generated__/config/front_matter/templates/block-hero.yml, .tina/__generated__/config/front_matter/templates/page.yml, .tina/__generated__/config/settings.yml, .tina/front_matter/templates/block-cta.yml, .tina/front_matter/templates/block-hero.yml, .tina/schema.ts, .tina/settings.yml, content/pages/home.md, package.json, pages/[[...slug]].tsx, yarn.lock
This is using the canary release for the cli changes. To be discussed
=> Use .ts config for Tina schema instead of yml

README.md
apply @jbevis feedback from our session
Note: the env variable is still using REALM and the App is using register Organization.
=> docs: apply feedback

README.md
=> use prod dashboard url

components/helper-components.tsx, components/landing-page.tsx, pages/_document.js
A couple of tags where missing that are good for accessibility. I added them in.
=> added accessibility meta tags and title

package.json, yarn.lock
Coordinate update with https://github.com/tinacms/teams-serverless/pull/385
=> Update Tina CLI

README.md
First-time users should know about minimal requirements before installing the starter.
=> docs: requirements

LICENSE, NOTICE
=> add LICENSE

content/marketing-pages/index.md
The diagram is a bit overwhelming for someone coming to the starter to figure out.
=> Remove the whimsical image for now

README.md
Links to our help channels for people to provide feedback.
=> docs: Getting help

.tina/__generated__/schema.gql, .tina/__generated__/types.ts, package.json, yarn.lock
=> chore(deps): bump tina-graphql-gateway

components/helper-components.tsx
Link to latest version of the client documentation
=> docs: link to production

package.json, pages/_app.js, yarn.lock
update to latest tina deps. 
This fixes media as well as a few other things.
=> chore(deps): tinacms 0.5.0

pages/_app.js
Reverts tinacms/tina-cloud-starter#119
=> Revert "chore: Adds documentCreatorCallback"

README.md
[Preview](https://github.com/tinacms/tina-cloud-starter/tree/docs/README#readme)
Link to our new Getting Started Guide: https://tina.io/guides/tina-cloud/starter/overview/
=> docs: lighter README

.tina/__generated__/_schema.json, .tina/__generated__/config/schema.json, .tina/schema.ts, package.json, pages/_app.js, yarn.lock
=> add wysiwyg component for content fields

pages/_app.js
Not sure what we want to do here, we were controlling this with an env var but it's more clear where to configure it now that hardcoding might be easier?
=> Add edit button by default

components/header.tsx
Fixes #123 
I have fixed the strange nav behaviour when not in edit mode. But some of it still happens when in edit mode. This could be a bug with TinaCMS. @DirtyF or @spbyrne Is it worth merging this so at least it is half fixed? We can revisit the larger issue in another PR.
=> WIP: fixed navigation

components/post.tsx
This decreases the blog details page title leading.
=> fix post title leading

.env.local.sample
=> fix: do no set edit with local

package.json, yarn.lock
this appears to fix #123 for me, hoping someone can confirm
=> upgrade tinacms to 0.51.0

components/header.tsx
Fixes https://github.com/tinacms/tina-cloud-starter/issues/143
(when paired with its sister PR: https://github.com/tinacms/tinacms/pull/1988 from `tinacms`)
=> fix: Fixes keys on nav items in the header

package.json, pages/[filename].tsx, yarn.lock
I removed the filename from the query as the bug that was requiring it to be there was fixed.
=> update packages and removed code

package.json, pages/posts/[filename].tsx, yarn.lock
Brings fixes for https://github.com/tinacms/tinacms/issues/1945 and https://github.com/tinacms/tina-cloud-starter/issues/147 into starter, as well as many other improvements from the [latest release](https://github.com/tinacms/tinacms/pull/2012)
=> Update to latest tina deps, fix document creation flow

.tina/__generated__/_graphql.json, .tina/__generated__/_schema.json, .tina/__generated__/config/schema.json, .tina/__generated__/schema.gql, .tina/__generated__/types.ts, .tina/schema.ts, components/post.tsx, components/posts.tsx, content/posts/anotherPost.md, content/posts/voteForPedro.md, package.json, pages/posts/[filename].tsx, yarn.lock
PR will make necessary changes to the starter to leverage recent changes to the TinaCMS APIs.
=> Update starter to use latest Tina APIs.

package.json, yarn.lock
Updates packages to the latest.
=> updated packages.

package.json, yarn.lock
Updating to the latest Tina Packages
=> Chore: Updating to the new packages.

package.json
Should fix https://github.com/tinacms/tinacms/issues/2379
=> remove yarn from package.json

.github/dependabot.yml
Auto-pr tinacms version updates
=> Auto-pr tinacms version updates

package.json, pages/_app.tsx, yarn.lock
This implementation was a bit more complicated than the others, as it uses useQuery at the root level. We may want to consider splitting this into it's own container within `tinacms`
=> implement useTina hook

.gitignore, components/header.tsx
- Fix the main menu to show the correct active item
- Add ".idea" for .gitignore file
- Replacing closing tag with self closing
=> Fix main menu current item underline

.tina/__generated__/_schema.json, .tina/schema.ts
Fixes authors when in admin mode.
=> Fix author when in admin mode.

pages/[filename].tsx
=> remove rogue semi colon

.tina/schema.ts
=> Added new and improved nav link labels to CMS

tsconfig.json
https://github.com/tinacms/tinacms/issues/3091
=> Specify 'react' for 'jsx' argument in tsconfig.json

components/blocks/hero.tsx
This updates the hero styles so the side-by-side layout is used at smaller screen sizes.
=> Hero Reponsive Fix

package.json
- pnpm throws an error on this resolution
=> remove _#important

package.json, pnpm-lock.yaml
This change:
- Provides a version bump to the tinacms and [at]tincms/cli packages
- Includes a complete regeneration of the `pnpm-lock.json` file
=> ⬆️ Upgrade - tinacms, [at]tinacms/cli

components/blocks/hero.tsx
Missed a type issue. Attempts to fix: https://github.com/tinacms/tinacms/actions/runs/15846139436/job/44668658415
=> chore: fix type issue
